In [ ]:
## Activate the packages required
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [ ]:
## Load the data
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
# check the number of rows & columns
df.shape

(1338, 7)

In [ ]:
# check for missing values
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
# convert all categorical variables (sex, smoker, region) into dummy nominal variables
df['sex'] = df['sex'].apply({'male':0, 'female':1}.get)
df['smoker'] = df['smoker'].apply({'yes':1, 'no':0}.get)
df['region'] = df['region'].apply({'southwest':1, 'southeast':2,'northwest':3,'northeast':4}.get)
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    1  27.900         0       1       1  16884.92400
1   18    0  33.770         1       0       2   1725.55230
2   28    0  33.000         3       0       2   4449.46200
3   33    0  22.705         0       0       3  21984.47061
4   32    0  28.880         0       0       3   3866.85520

In [ ]:
# Define the IVs & DV (STEP-1 in Machine Learning Modeling)
x = df.drop(['charges'], axis=1)   ## except charges, all other variables are IVs
y = df.charges   # charges is the DV

In [ ]:
# Split the data into Training & Test Data (Step-2 in ML Modelling)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((936, 6), (402, 6), (936,), (402,))

In [ ]:
# Define the ML Model (Step-3 in ML Modelling)
model = LinearRegression()

In [ ]:
# Fit the model (Step-4 in ML Modelling)
model.fit(x_train, y_train)  # estimate the alpha and betas

In [ ]:
print(model.intercept_, model.coef_, model.score(x,y))

-13560.594627417398 [  261.62568984  -109.64719595   344.54483066   424.37016596
 23620.80252148   326.46262527] 0.7504776237328423

In [ ]:
# Predict using the model for test data (Step-5 of ML Modelling)
predictions = model.predict(x_test)

In [ ]:
# Measure the accuracy using suitable metric (Step-6 of ML Modelling)
print("R2 score:", r2_score(y_test, predictions))

R2 score: 0.7694415927057693

In [ ]:
# User input data for prediction using the above model
new_cust_data = {'age': 30, 'sex':1, 'bmi': 30, 'children': 4, 'smoker': 1, 'region':1}
index = [0]
new_cust_data_df = pd.DataFrame(new_cust_data, index)
new_cust_data_df

   age  sex  bmi  children  smoker  region
0   30    1   30         4       1       1

In [ ]:
# Prediction
predicted_charges = model.predict(new_cust_data_df)
print("The charges for this customer are:", predicted_charges)

The charges for this customer are: [30159.61960218]